import * as React from 'react';
import * as Finder from '../Finder';
import { CellFormatter, EntityFormatter } from '../Finder';
import { ResultTable, ResultRow, FindOptionsParsed, FilterOptionParsed, QueryDescription, ColumnOptionParsed, ColumnDescription, Pagination, QueryToken, QueryRequest } from '../FindOptions';
import { Lite, Entity, ModifiableEntity } from '../Signum.Entities';
import { TypeInfo } from '../Reflection';
import * as Navigator from '../Navigator';
import { AbortableRequest } from '../Services';
import { MarkedRowsDictionary, MarkedRow } from './ContextualItems';
import { ContextMenuPosition } from './ContextMenu';
import { ISimpleFilterBuilder } from './SearchControl';
import { MaxHeightProperty } from 'csstype';
import "./Search.css";
import { ButtonBarElement } from '../TypeContext';
export interface ShowBarExtensionOption {
}
export interface SearchControlLoadedProps {
    findOptions: FindOptionsParsed;
    queryDescription: QueryDescription;
    querySettings: Finder.QuerySettings | undefined;
    formatters?: {
        [token: string]: CellFormatter;
    };
    rowAttributes?: (row: ResultRow, columns: string[]) => React.HTMLAttributes<HTMLTableRowElement> | undefined;
    entityFormatter?: EntityFormatter;
    extraButtons?: (searchControl: SearchControlLoaded) => (ButtonBarElement | null | undefined | false)[];
    getViewPromise?: (e: ModifiableEntity | null) => (undefined | string | Navigator.ViewPromise<ModifiableEntity>);
    maxResultsHeight?: MaxHeightProperty<string | number> | any;
    tag?: string | {};
    searchOnLoad: boolean;
    allowSelection: boolean;
    showContextMenu: boolean | "Basic";
    showSelectedButton: boolean;
    hideButtonBar: boolean;
    hideFullScreenButton: boolean;
    showHeader: boolean | "PinnedFilters";
    showBarExtension: boolean;
    showBarExtensionOption?: ShowBarExtensionOption;
    showFilters: boolean;
    showSimpleFilterBuilder: boolean;
    showFilterButton: boolean;
    showSystemTimeButton: boolean;
    showGroupButton: boolean;
    showFooter: boolean;
    allowChangeColumns: boolean;
    allowChangeOrder: boolean;
    create: boolean;
    navigate: boolean | "InPlace";
    largeToolbarButtons: boolean;
    avoidAutoRefresh: boolean;
    avoidChangeUrl: boolean;
    refreshKey: string | number | undefined;
    simpleFilterBuilder?: (qd: QueryDescription, initialFilterOptions: FilterOptionParsed[], search: () => void) => React.ReactElement<any> | undefined;
    enableAutoFocus: boolean;
    onCreate?: () => void;
    onDoubleClick?: (e: React.MouseEvent<any>, row: ResultRow) => void;
    onNavigated?: (lite: Lite<Entity>) => void;
    onSelectionChanged?: (rows: ResultRow[]) => void;
    onFiltersChanged?: (filters: FilterOptionParsed[]) => void;
    onHeighChanged?: () => void;
    onSearch?: (fo: FindOptionsParsed, dataChange: boolean) => void;
    onResult?: (table: ResultTable, dataChange: boolean) => void;
}
export interface SearchControlLoadedState {
    resultTable?: ResultTable;
    simpleFilterBuilder?: React.ReactElement<any>;
    selectedRows?: ResultRow[];
    markedRows?: MarkedRowsDictionary;
    isSelectOpen: boolean;
    resultFindOptions?: FindOptionsParsed;
    searchCount?: number;
    dragColumnIndex?: number;
    dropBorderIndex?: number;
    currentMenuItems?: React.ReactElement<any>[];
    contextualMenu?: {
        position: ContextMenuPosition;
        columnIndex: number | null;
        columnOffset?: number;
        rowIndex: number | null;
    };
    showFilters: boolean;
    editingColumn?: ColumnOptionParsed;
    lastToken?: QueryToken;
}
export default class SearchControlLoaded extends React.Component<SearchControlLoadedProps, SearchControlLoadedState> {
    constructor(props: SearchControlLoadedProps);
    componentWillMount(): void;
    componentWillReceiveProps(props: SearchControlLoadedProps): void;
    isUnmounted: boolean;
    componentWillUnmount(): void;
    entityColumn(): ColumnDescription;
    entityColumnTypeInfos(): TypeInfo[];
    canFilter(): boolean;
    getQueryRequest(): QueryRequest;
    doSearchPage1(): void;
    resetResults(continuation: () => void): void;
    abortableSearch: AbortableRequest<QueryRequest, ResultTable>;
    doSearch(dataChanged?: boolean): Promise<void>;
    notifySelectedRowsChanged(): void;
    simpleFilterBuilderInstance?: ISimpleFilterBuilder;
    getFindOptionsWithSFB(): Promise<FindOptionsParsed>;
    handlePagination: (p: Pagination) => void;
    handleOnContextMenu: (event: React.MouseEvent<any, MouseEvent>) => void;
    handleColumnChanged: (token: QueryToken | undefined) => void;
    handleColumnClose: () => void;
    handleFilterTokenChanged: (token: QueryToken | undefined) => void;
    handleFiltersChanged: () => void;
    handlePinnedFilterChanged: () => void;
    handleHeightChanged: () => void;
    handleFiltersKeyUp: (e: React.KeyboardEvent<HTMLDivElement>) => void;
    componentDidMount(): void;
    fixScroll(): void;
    containerDiv?: HTMLDivElement | null;
    thead?: HTMLTableSectionElement | null;
    render(): JSX.Element;
    handleSearchClick: (ev: React.MouseEvent<any, MouseEvent>) => void;
    handleToggleFilters: () => void;
    handleSystemTimeClick: () => void;
    handleToggleGroupBy: () => void;
    renderToolBar(): JSX.Element;
    chooseType(): Promise<string | undefined>;
    handleCreate: (ev: React.MouseEvent<any, MouseEvent>) => void;
    handleFullScreenClick: (ev: React.MouseEvent<any, MouseEvent>) => void;
    createTitle(): string;
    getSelectedEntities(): Lite<Entity>[];
    handleSelectedToggle: () => void;
    loadMenuItems(): void;
    markRows: (dic: MarkedRowsDictionary) => void;
    renderSelectedButton(): ButtonBarElement | null;
    handleContextOnHide: () => void;
    handleQuickFilter: () => void;
    handleInsertColumn: () => void;
    handleEditColumn: () => void;
    handleRemoveColumn: () => void;
    renderContextualMenu(): JSX.Element | null;
    allSelected(): boolean;
    handleToggleAll: () => void;
    handleHeaderClick: (e: React.MouseEvent<any, MouseEvent>) => void;
    handleHeaderDragStart: (de: React.DragEvent<any>, dragIndex: number) => void;
    handleHeaderDragEnd: (de: React.DragEvent<any>) => void;
    getOffset(pageX: number, rect: ClientRect, margin: number): 1 | 0 | undefined;
    handlerHeaderDragOver: (de: React.DragEvent<any>, columnIndex: number) => void;
    handleHeaderDrop: (de: React.DragEvent<any>) => void;
    renderHeaders(): React.ReactNode;
    canOrder(column: ColumnOptionParsed): boolean;
    orderClassName(column: ColumnOptionParsed): string;
    handleChecked: (event: React.ChangeEvent<HTMLInputElement>) => void;
    handleDoubleClick: (e: React.MouseEvent<any, MouseEvent>, row: ResultRow) => void;
    renderRows(): React.ReactNode;
    handleOnNavigated: (lite: Lite<Entity>) => void;
    getMarkedRow(entity: Lite<Entity>): MarkedRow | undefined;
}
//# sourceMappingURL=SearchControlLoaded.d.ts.map