import { TypeContext, StyleContext, StyleOptions, FormGroupStyle, FormSize, IRenderButtons } from './TypeContext';
export { TypeContext, StyleContext, StyleOptions, FormGroupStyle, FormSize, IRenderButtons };
import { PropertyRoute, Binding, ReadonlyBinding } from './Reflection';
export { Binding, ReadonlyBinding, PropertyRoute };
import { LineBase, LineBaseProps, tasks, ChangeEvent } from './Lines/LineBase';
export { LineBase, LineBaseProps, tasks, ChangeEvent };
import { FormGroup, FormGroupProps } from './Lines/FormGroup';
export { FormGroup, FormGroupProps };
import { FormControlReadonly, FormControlReadonlyProps } from './Lines/FormControlReadonly';
export { FormControlReadonly, FormControlReadonlyProps };
import { ValueLine, ValueLineType, ValueLineProps, OptionItem } from './Lines/ValueLine';
export { ValueLine, ValueLineType, ValueLineProps, OptionItem };
export { RenderEntity } from './Lines/RenderEntity';
import { EntityBase } from './Lines/EntityBase';
export { EntityBase };
export { AutocompleteConfig, FindOptionsAutocompleteConfig, LiteAutocompleteConfig } from './Lines/AutoCompleteConfig';
export { EntityLine } from './Lines/EntityLine';
export { EntityCombo } from './Lines/EntityCombo';
export { EntityDetail } from './Lines/EntityDetail';
import { EntityListBase, EntityListBaseProps } from './Lines/EntityListBase';
export { EntityListBase, EntityListBaseProps };
export { EntityList } from './Lines/EntityList';
export { EntityRepeater } from './Lines/EntityRepeater';
export { EntityTabRepeater } from './Lines/EntityTabRepeater';
export { EntityStrip } from './Lines/EntityStrip';
export { EntityCheckboxList } from './Lines/EntityCheckboxList';
export { EnumCheckboxList } from './Lines/EnumCheckboxList';
export { MultiValueLine } from './Lines/MultiValueLine';
import { EntityTable, EntityTableColumn, EntityTableRow } from './Lines/EntityTable';
import DynamicComponent from './Lines/DynamicComponent';
export { DynamicComponent };
export { EntityTable, EntityTableColumn, EntityTableRow };
export declare function taskSetNiceName(lineBase: LineBase<any, any>, state: LineBaseProps): void;
export declare function taskSetUnit(lineBase: LineBase<any, any>, state: LineBaseProps): void;
export declare function taskSetFormat(lineBase: LineBase<any, any>, state: LineBaseProps): void;
export declare function taskSetReadOnly(lineBase: LineBase<any, any>, state: LineBaseProps): void;
export declare function taskSetMandatory(lineBase: LineBase<any, any>, state: LineBaseProps): void;
export declare function taskSetMove(lineBase: LineBase<any, any>, state: LineBaseProps): void;
export declare let maxValueLineSize: number;
export declare function taskSetHtmlProperties(lineBase: LineBase<any, any>, state: LineBaseProps): void;
//# sourceMappingURL=Lines.d.ts.map