import { MessageKey, EnumType } from './Reflection';
export declare const ColumnOptionsMode: EnumType<ColumnOptionsMode>;
export declare type ColumnOptionsMode = "Add" | "Remove" | "Replace" | "InsertStart";
export declare const FilterGroupOperation: EnumType<FilterGroupOperation>;
export declare type FilterGroupOperation = "And" | "Or";
export declare const FilterOperation: EnumType<FilterOperation>;
export declare type FilterOperation = "EqualTo" | "DistinctTo" | "GreaterThan" | "GreaterThanOrEqual" | "LessThan" | "LessThanOrEqual" | "Contains" | "StartsWith" | "EndsWith" | "Like" | "NotContains" | "NotStartsWith" | "NotEndsWith" | "NotLike" | "IsIn" | "IsNotIn";
export declare const FilterType: EnumType<FilterType>;
export declare type FilterType = "Integer" | "Decimal" | "String" | "DateTime" | "Lite" | "Embedded" | "Boolean" | "Enum" | "Guid";
export declare const OrderType: EnumType<OrderType>;
export declare type OrderType = "Ascending" | "Descending";
export declare const PaginationMode: EnumType<PaginationMode>;
export declare type PaginationMode = "All" | "Firsts" | "Paginate";
export declare module QueryTokenMessage {
    const _0As1: MessageKey;
    const And: MessageKey;
    const AnyEntity: MessageKey;
    const As0: MessageKey;
    const Check: MessageKey;
    const Column0NotFound: MessageKey;
    const Count: MessageKey;
    const Date: MessageKey;
    const DateTime: MessageKey;
    const Day: MessageKey;
    const DayOfWeek: MessageKey;
    const DayOfYear: MessageKey;
    const DecimalNumber: MessageKey;
    const Embedded0: MessageKey;
    const GlobalUniqueIdentifier: MessageKey;
    const Hour: MessageKey;
    const ListOf0: MessageKey;
    const Millisecond: MessageKey;
    const Minute: MessageKey;
    const Month: MessageKey;
    const MonthStart: MessageKey;
    const Quarter: MessageKey;
    const QuarterStart: MessageKey;
    const WeekStart: MessageKey;
    const HourStart: MessageKey;
    const MinuteStart: MessageKey;
    const SecondStart: MessageKey;
    const MoreThanOneColumnNamed0: MessageKey;
    const Number: MessageKey;
    const Of: MessageKey;
    const Second: MessageKey;
    const Text: MessageKey;
    const Year: MessageKey;
    const WeekNumber: MessageKey;
    const _0Steps1: MessageKey;
    const Step0: MessageKey;
    const Length: MessageKey;
    const _0HasValue: MessageKey;
    const HasValue: MessageKey;
    const Modulo0: MessageKey;
    const _0Mod1: MessageKey;
    const Null: MessageKey;
    const Not: MessageKey;
    const Distinct: MessageKey;
}
export declare const SystemTimeMode: EnumType<SystemTimeMode>;
export declare type SystemTimeMode = "AsOf" | "Between" | "ContainedIn" | "All";
export declare const UniqueType: EnumType<UniqueType>;
export declare type UniqueType = "First" | "FirstOrDefault" | "Single" | "SingleOrDefault" | "SingleOrMany" | "Only";
//# sourceMappingURL=Signum.Entities.DynamicQuery.d.ts.map